export const metadata = {
  title: "GetColor.io | Privacy Policy",
  description: "Privacy Policy for GetColor.io",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p>Last updated: September 26, 2024</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        <strong>
          We want to emphasize that we do not collect, process, store, or
          transmit any video data from your device's camera. All video
          processing occurs locally on your device, and no video data is sent to
          our servers or any third parties.
        </strong>
      </p>
      <p>
        By using the Service, You agree to the collection and use of information
        in accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>

      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <p>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to GetColor.io.
          </p>
        </li>
        <li>
          <p>
            <strong>Country</strong> refers to: Portugal.
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone, or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>Website</strong> refers to GetColor.io, accessible from
            <a
              href="https://getcolor.io"
              rel="external nofollow noopener"
              target="_blank"
            >
              https://getcolor.io
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </p>
        </li>
      </ul>

      <h2>Collecting and Using Your Data</h2>

      <h3>Types of Data Collected</h3>

      <h4>Personal Data</h4>
      <p>
        <strong>
          We do not collect any personally identifiable information ("Personal
          Data") that can be used to contact or identify You.
        </strong>
      </p>

      <h4>Usage Data</h4>
      <p>We may collect Usage Data when you access the Service.</p>
      <p>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g., IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers, and other
        diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers, and other
        diagnostic data.
      </p>

      <h4>Video Data</h4>
      <p>
        <strong>
          Our Service requires access to your device's camera to provide
          real-time color detection functionality. However, we do not collect,
          process, store, or transmit any video data from your device. All video
          processing occurs locally on your device, and no video data is sent to
          our servers or any third parties.
        </strong>
      </p>

      <h4>Cookies and Tracking Technologies</h4>
      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. We ask for your explicit
        consent to use any non-essential or third-party Cookies. If You do not
        provide consent, only essential Cookies will be used.
      </p>
      <p>
        For more detailed information on the Cookies we use and your choices
        regarding Cookies, please refer to our{" "}
        <a href="/cookie-policy">Cookies Policy</a>.
      </p>

      <h3>Use of Your Data</h3>
      <p>
        Since we do not collect Personal Data, we primarily use Usage Data to
        monitor and analyze the use of our Service and to ensure its security
        and performance.
      </p>

      <h3>Retention of Your Data</h3>
      <p>
        The Company will retain Usage Data for internal analysis purposes. Usage
        Data is generally retained for a shorter period of time, except when
        this data is used to strengthen the security or to improve the
        functionality of Our Service.
      </p>

      <h3>Transfer of Your Data</h3>
      <p>
        Your information, including Usage Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country, or other governmental jurisdiction where the
        data protection laws may differ than those from Your jurisdiction.
      </p>
      <p>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>

      <h3>Disclosure of Your Data</h3>
      <p>
        Since we do not collect Personal Data, we do not disclose your Personal
        Data to third parties. However, we may disclose Usage Data under certain
        circumstances:
      </p>
      <ul>
        <li>To comply with a legal obligation</li>
        <li>To protect and defend the rights or property of the Company</li>
        <li>
          To prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          To protect the personal safety of Users of the Service or the public
        </li>
        <li>To protect against legal liability</li>
      </ul>

      <h3>Security of Your Data</h3>
      <p>
        The security of Your data is important to Us. While we do not collect
        Personal Data, we strive to use commercially acceptable means to protect
        any information we hold.
      </p>

      <h2>Your Rights Under GDPR</h2>
      <p>
        If You are a resident of the European Economic Area (EEA), You have
        certain data protection rights. Our goal is to take reasonable steps to
        allow You to correct, amend, delete, or limit the use of Your Usage
        Data.
      </p>
      <p>
        As we do not collect Personal Data, the rights related to Personal Data
        may not apply. However, You have the right to:
      </p>
      <ul>
        <li>Be informed about the use of Cookies and tracking technologies.</li>
        <li>
          Provide or withdraw consent for non-essential Cookies and third-party
          Cookies.
        </li>
        <li>Access information about the Cookies used on our Service.</li>
      </ul>

      <h2>Children's Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>

      <h2>Links to Other Websites</h2>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third-party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies, or practices of any third-party sites or services.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul>
        <li>
          By email: <a href="mailto:legal@getcolor.io">legal@getcolor.io</a>
        </li>
      </ul>
    </>
  );
}
